### ISSUE TITLE
Channels and Service on client page

### ISSUE THREAD

**Issue by flintdesign** [FlintMade/mediaplus#117]
They would like to move Channels and service to the bottom of the client list and align Expertise to the client list items associated?

![image](https://user-images.githubusercontent.com/12940384/28441849-cc3d0548-6d61-11e7-98e9-a3e38430605d.png)

![image](https://user-images.githubusercontent.com/12940384/28442620-110329b0-6d66-11e7-9129-95cf53a5adc2.png)

**Comment by melanierichards** [comment]
@wes-anderson I wanted to mention that with the rearrangement of this page (http://mediaplus.flintmade.co/clients/) I made a couple changes to margins. The spacing between the expertise area and the client rows gets the normal page section spacing, so that they feel more related (used to have large spacing). The section at the bottom, channels and services, gets the larger section spacing that used to be between the top section and the client rows; this is so that it'll feel unrelated to the client rows. Please let me know if you'd like to switch either of these spacings between standard/large spacing.
