### ISSUE TITLE
Mobile About Page - Team Photos

### ISSUE THREAD

**Issue by wes-anderson** [FlintMade/mediaplus#21]
The team photos all appear to be different sizes.

**Comment by melanierichards** [comment]
The way I've built the team blocks is that the height of the box is dependent on the height of the text content, and the image fills in the background. This makes it so that the text never overflows the box; if the box were sized based on the image, the client would have to test to make sure their text doesn't overflow at all widths.

When the boxes are in rows, I can make the sizing consistent using flexbox, but that ability isn't available when they're stacked on mobile.

One way to make it more consistent is to apply a minimum height to all the blocks on the mobile view. But I think we should save that for when we have real content in there. Sound good?

**Comment by wes-anderson** [comment]
Yeah that sounds good. We can also make areas like this a character limit to help ensure mobile friendly.

**Comment by melanierichards** [comment]
^ we decided to do that (375 chars)
